stages:
  - storage
  - messaging
  - app

deploy_efs:
  image:
    name: lachlanevenson/k8s-kubectl:latest
    entrypoint: ["/bin/sh", "-c"]
  stage: storage
  environment:
    name: live
  when: manual
  script:
    - kubectl version
    - cd EKS/02-EFS
    - kubectl create namespace project-logistics
    - kubectl apply -f create-rbac.yaml --namespace=project-logistics
    - kubectl apply -f create-efs-provisioner.yaml --namespace=project-logistics

deploy_kafka:
  image:
    name: lachlanevenson/k8s-kubectl:latest
    entrypoint: ["/bin/sh", "-c"]
  stage: messaging
  environment:
    name: live
  when: manual
  before_script:
    - apk add --update curl && rm -rf /var/cache/apk/*
    - apk update && apk add bash
    - apk add --update openssl && rm -rf /var/cache/apk/*
  script:
    - kubectl version
    - cd EKS/05-Kafka
    - mkdir eks-kafka-strimzi
    - cd eks-kafka-strimzi
    - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > get_helm.sh
    - chmod +x get_helm.sh
    - ./get_helm.sh
    - cd ../
    - kubectl apply -f rbac.yaml
    - helm init --service-account=tiller
    - helm repo add strimzi http://strimzi.io/charts/
    - helm search strim
    - helm install strimzi/strimzi-kafka-operator --namespace=project-logistics
    - sleep 60
    - kubectl get all --namespace=project-logistics
    - kubectl apply -f kafka-cluster.Kafka.yaml --namespace=project-logistics
    - sleep 180
    - kubectl get statefulsets.apps,pod,deployments,svc --namespace=project-logistics
    - kubectl get pv,pvc --namespace=project-logistics
    - kubectl apply -f create-topics.yaml --namespace=project-logistics
    - kubectl create -f kafka-host-configmap.yaml --namespace=project-logistics

deploy_auth:
  image:
    name: lachlanevenson/k8s-kubectl:latest
    entrypoint: ["/bin/sh", "-c"]
  stage: app
  environment:
    name: live
  when: manual
  script:
    - kubectl version
    - cd EKS/03-PostgreSQL
    - kubectl create -f authdb-configmap.yaml --namespace=project-logistics
    - kubectl create -f create-storage.yaml --namespace=project-logistics
    - kubectl create -f deploy-postgres-auth.yaml --namespace=project-logistics
    - cd ../04-Auth
    - kubectl create -f deploy-auth.yaml --namespace=project-logistics

deploy_order:
  image:
    name: lachlanevenson/k8s-kubectl:latest
    entrypoint: ["/bin/sh", "-c"]
  stage: app
  environment:
    name: live
  script:
    - kubectl version
    - cd EKS/06-OrderApp
    - kubectl create -f orderdb-configmap.yaml --namespace=project-logistics
    - kubectl create -f deploy-postgres-order.yaml --namespace=project-logistics
    - kubectl create -f deploy-order-app.yaml --namespace=project-logistics
  dependencies:
    - deploy_auth

deploy_query:
  image:
    name: lachlanevenson/k8s-kubectl:latest
    entrypoint: ["/bin/sh", "-c"]
  stage: app
  environment:
    name: live
  script:
    - kubectl version
    - cd EKS/07-QueryApp
    - kubectl create -f querydb-configmap.yaml --namespace=project-logistics
    - kubectl create -f deploy-postgres-query.yaml --namespace=project-logistics
    - kubectl create -f deploy-query-app.yaml --namespace=project-logistics
  dependencies:
    - deploy_auth

deploy_stock:
  image:
    name: lachlanevenson/k8s-kubectl:latest
    entrypoint: ["/bin/sh", "-c"]
  stage: app
  environment:
    name: live
  script:
    - kubectl version
    - cd EKS/08-StockApp
    - kubectl create -f stockdb-configmap.yaml --namespace=project-logistics
    - kubectl create -f deploy-postgres-stock.yaml --namespace=project-logistics
    - kubectl create -f deploy-stock-app.yaml --namespace=project-logistics
  dependencies:
    - deploy_auth

deploy_shipment:
  image:
    name: lachlanevenson/k8s-kubectl:latest
    entrypoint: ["/bin/sh", "-c"]
  stage: app
  environment:
    name: live
  script:
    - kubectl version
    - cd EKS/09-ShipmentApp
    - kubectl create -f deploy-shipment-app.yaml --namespace=project-logistics
  dependencies:
    - deploy_order
    - deploy_auth
