apiVersion: v1
kind: Service
metadata:
  name: logistics-order-service
  labels:
    app: logistics
spec:
  ports:
    - port: 9001
      targetPort: 9001
  selector:
    app: order-service
    tier: apis
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: logistics-order-service
  labels:
    app: logistics
spec:
  selector:
    matchLabels:
      app: order-service
      tier: apis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: order-service
        tier: apis
    spec:
      containers:
        - image: amitmahajan/logistics-order-api:0.2
          name: order-service
          env:
            - name: POSTGRESQL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: orderdb-config
                  key: POSTGRES_USER
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: orderdb-config
                  key: POSTGRES_PASSWORD
            - name: DB_HOST_IP
              value: logistics-order-db
            - name: AUTH_SERVER_URL
              value: logistics-auth-service
            - name: KAFKA_INFRA_HOST_IP
              valueFrom:
                configMapKeyRef:
                  name: kafkahost-config
                  key: KAFKA_HOST
          ports:
            - containerPort: 9001
              name: order-service
