apiVersion: v1
kind: Service
metadata:
  name: logistics-order-db
  labels:
    app: order
spec:
  ports:
    - port: 5432
  selector:
    app: order
    tier: database
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: logistics-order-db
  labels:
    app: order
spec:
  selector:
    matchLabels:
      app: order
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: order
        tier: database
    spec:
      containers:
        - image: postgres:latest
          name: postgresdb
          envFrom:
            - configMapRef:
                name: orderdb-config
          ports:
            - containerPort: 5432
              name: order-db
