apiVersion: v1
kind: Service
metadata:
  name: logistics-query-service
  labels:
    app: query
spec:
  selector:
    app: query
    tier: apis
  ports:
    - name: http
      port: 9003
  type: ClusterIP
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: logistics-query-service
  labels:
    app: query
spec:
  selector:
    matchLabels:
      app: query
      tier: apis
  replicas: 1
  template:
    metadata:
      labels:
        app: query
        tier: apis
        version: latest
    spec:
      containers:
        - image: amitmahajan/query-service:2.3
          name: query-service
          env:
            - name: POSTGRESQL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: querydb-config
                  key: POSTGRES_USER
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: querydb-config
                  key: POSTGRES_PASSWORD
            - name: DB_HOST_IP
              value: logistics-query-db
            - name: AUTH_SERVER_URL
              value: logistics-auth-service
            - name: KAFKA_INFRA_HOST_IP
              valueFrom:
                configMapKeyRef:
                  name: kafkahost-config
                  key: KAFKA_HOST
          ports:
            - containerPort: 9003
              name: query-service
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: logistics-query-service-upcoming
  labels:
    app: query
spec:
  selector:
    matchLabels:
      app: query
      tier: apis
  replicas: 1
  template:
    metadata:
      labels:
        app: query
        tier: apis
        version: upcoming
    spec:
      containers:
        - image: amitmahajan/query-service:2.6-upcoming
          name: query-service
          env:
            - name: POSTGRESQL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: querydb-config
                  key: POSTGRES_USER
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: querydb-config
                  key: POSTGRES_PASSWORD
            - name: DB_HOST_IP
              value: logistics-query-db
            - name: AUTH_SERVER_URL
              value: logistics-auth-service
            - name: KAFKA_INFRA_HOST_IP
              valueFrom:
                configMapKeyRef:
                  name: kafkahost-config
                  key: KAFKA_HOST
          ports:
            - containerPort: 9003
              name: query-service