apiVersion: v1
kind: Service
metadata:
  name: logistics-gateway-service
  labels:
    app: logistics
spec:
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: gateway-service
    tier: apis
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: logistics-gateway-service
  labels:
    app: logistics
spec:
  selector:
    matchLabels:
      app: gateway-service
      tier: apis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gateway-service
        tier: apis
    spec:
      containers:
        - image: amitmahajan/gateway:2.1
          name: gateway-service
          env:
            - name: AUTH_SERVER_URL
              value: logistics-auth-service
            - name: ORDER_SERVER_URL
              value: logistics-order-service
            - name: STOCK_SERVER_URL
              value: logistics-stock-service
            - name: SHIPMENT_SERVER_URL
              value: logistics-shipment-service
            - name: QUERY_SERVER_URL
              value: logistics-query-service
          ports:
            - containerPort: 9090
              name: gateway-svc
