apiVersion: v1
kind: Service
metadata:
  name: logistics-auth-service
  labels:
    app: auth
spec:
  ports:
    - name: http
      port: 8090
      nodePort: 30090
  type: NodePort
  selector:
    app: auth
    tier: apis
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: logistics-auth-service
  labels:
    app: auth
spec:
  selector:
    matchLabels:
      app: auth
      tier: apis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: auth
        tier: apis
    spec:
      containers:
        - image: amitmahajan/logistics-auth:0.1
          name: auth-service
          env:
            - name: POSTGRESQL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: authdb-config
                  key: POSTGRES_USER
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: authdb-config
                  key: POSTGRES_PASSWORD
            - name: DB_AUTH_IP
              value: logistics-auth-db
          ports:
            - containerPort: 8090
              name: auth-service
