apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster
  region: eu-west-2

nodeGroups:
  - name: node-group-one
    instanceType: t3.medium
    desiredCapacity: 3
    ssh: # use existing EC2 key
      publicKeyPath: /Users/amitmahajan/.ssh/eks-cluster-key.pub
  #- name: ng-group-mixed
  #  minSize: 3
  #  maxSize: 5
  #  instancesDistribution:
  #    maxPrice: 0.2
  #    instanceTypes: ["t2.small", "t3.small"]
  #    onDemandBaseCapacity: 0
  #    onDemandPercentageAboveBaseCapacity: 50
  #  ssh:
  #    publicKeyPath: /Users/amitmahajan/.ssh/eks-istio.pem
