apiVersion: v1
kind: Service
metadata:
  name: logistics-auth-db
  labels:
    app: auth
spec:
  ports:
    - port: 5432
  selector:
    app: auth
    tier: database
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: logistics-auth-db
  labels:
    app: auth
spec:
  selector:
    matchLabels:
      app: auth
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: auth
        tier: database
    spec:
      containers:
        - image: postgres:latest
          name: auth-db
          envFrom:
            - configMapRef:
                name: authdb-config
          ports:
            - containerPort: 5432
              name: auth-db