kind: PersistentVolume
apiVersion: v1
metadata:
  name: efs-postgres-vol
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/efs-postgres-vol"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  volumeName: efs-postgres-vol
  resources:
    requests:
      storage: 1Gi