apiVersion: v1
kind: Service
metadata:
  name: logistics-supplychain-db
  labels:
    app: supplychain
spec:
  ports:
    - port: 5432
  selector:
    app: supplychain
    tier: database
  type: ClusterIP
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: logistics-supplychain-db
  labels:
    app: supplychain
spec:
  selector:
    matchLabels:
      app: supplychain
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: supplychain
        tier: database
    spec:
      containers:
        - image: postgres:latest
          name: postgresdb
          envFrom:
            - configMapRef:
                name: supplychaindb-config
          ports:
            - containerPort: 5432
              name: postgres-sc
          volumeMounts:
            - name: supplychaindb-persistent-storage
              mountPath: /var/lib/postgresql/supplychain/data
      volumes:
        - name: supplychaindb-persistent-storage
          persistentVolumeClaim:
            claimName: efs-postgres
