apiVersion: v1
kind: Service
metadata:
  name: logistics-supplychain-service
  labels:
    app: supplychain
spec:
  selector:
    app: supplychain
    tier: apis
  ports:
    - name: http
      port: 9092
  type: ClusterIP
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: logistics-supplychain-service
  labels:
    app: supplychain
spec:
  selector:
    matchLabels:
      app: supplychain
      tier: apis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: supplychain
        tier: apis
    spec:
      containers:
        - image: amitmahajan/supply-chain:2.3
          name: supplychain-service
          env:
            - name: POSTGRESQL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: supplychaindb-config
                  key: POSTGRES_USER
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: supplychaindb-config
                  key: POSTGRES_PASSWORD
            - name: DB_INFRA_HOST_IP
              value: logistics-supplychain-db
            - name: GATEWAY_URL
              value: logistics-gateway-service
            - name: KAFKA_INFRA_HOST_IP
              valueFrom:
                configMapKeyRef:
                  name: kafkahost-config
                  key: KAFKA_HOST
          ports:
            - containerPort: 9092
              name: sc-service
